repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
