repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
      - id: black

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.11.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
