repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
      - id: black
        language_version: python3.10
        exclude: processor/database/alembic/versions/

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.11.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
