[tool.ruff]
# Configuration for Ruff, Python Linter
line-length = 100
target-version = "py39"
exclude = [
    ".github",
    ".pytest_cache",
    "config",
    "doc",
    "docker-conf",
    "files",
    "logs",
    "templates",
    "venv",
    ".env",
    "processor/database/alembic"
]
select = ["E4", "E7", "E9", "F", "I"]

[tool.commitizen]
# Configuration for commitizen, git messages standard
name = "cz_conventional_commits"
version = "3.6.0"
tag_format = "v$version"


[tool.black]
py39 = true
include = '\.pyi?$'
force-exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | processor/database/alembic/versions/

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/'''