name: tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  ENTITY_SERVER_URL: ${{ secrets.ENTITY_SERVER_URL }}
  FEMINICIDE_API_KEY: ${{ secrets.FEMINICIDE_API_KEY }}
  FEMINICIDE_API_URL: ${{ secrets.FEMINICIDE_API_URL }}
  MC_API_TOKEN: ${{ secrets.MC_API_TOKEN }}
  MC_LEGACY_API_KEY: ${{ secrets.MC_LEGACY_API_KEY }}
  NEWSCATCHER_API_KEY: ${{ secrets.NEWSCATCHER_API_KEY }}
  DATABASE_URL: postgresql:///postgres:postgres@localhost:5432/story_processor_db2

jobs:

  tests:

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.8
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          ./scripts/download-models.sh
          alembic upgrade head

      - name: Test with pytest
        run: pytest
